import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export default function COC() {
    const router = useRouter();
    const [name, setName] = useState('');
  
    const handleSubmit = e => {
      e.preventDefault();
      const data = {
        name,
      };
      router.push(`/contact/${data['name']}`);
    };
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <form onSubmit={handleSubmit}>
            <label htmlFor="name">Name:</label>
            <input
              id="name"
              type="text"
              onChange={e => setName(e.target.value)}
            />
          </form>
        </main>
      </div>
    );
  }